- name: clone libdvdcss git repository
  git: repo=git://git.videolan.org/libdvdcss.git
       dest=/tmp/checkout
       version=1.2.13
       ssh_opts="-o StrictHostKeyChecking=no"

- name: compile libdvdcss
  shell: 'cd /tmp/checkout; {{ item }}'
  with_items:
    - autoreconf -i
    - ./configure --prefix=/usr/local
    - make 

- name: install libdvdcss
  become: yes
  shell: 'cd /tmp/checkout; {{ item }}'
  with_items:
    - make install

# create a directory if it doesn't exist
- file: path=/etc/ld.so.conf.d state=directory mode=0755

- name: copy ld configuration
  become: yes
  copy: src=libdvdcss.conf dest=/etc/ld.so.conf.d
  when: ansible_os_family == "Debian"

- name: ldconfig
  become: yes
  shell: 'ldconfig -v'

- name: install Handbrake
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - handbrake-cli
  when: ansible_os_family == "Debian"

# create a directory if it doesn't exist
- file: path=/usr/local/bin state=directory mode=0755

- name: copy dvdul script
  become: yes
  copy: src={{item.name}} dest=/usr/local/bin mode={{item.mode}}
  with_items:
    - { name: 'dvdul', mode: '0777' }
    - { name: 'dvdul.py', mode: '0644' }