- name: install buildpkgs packages
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - autoconf
    - build-essential
    - git
    - libtool
    - make
  when: ansible_os_family == "Debian"
